apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: "{{ template "name" . }}-{{ .Values.name }}"
  labels:
    app: "{{ template "name" . }}-{{ .Values.name }}"
    chart: "{{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}"
spec:
  {{- if eq .Values.strategy.type "RollingUpdate" }}
  strategy:
    type: {{ .Values.strategy.type }}
    rollingUpdate:
      maxSurge: {{ .Values.strategy.maxSurge }}
      maxUnavailable: {{ .Values.strategy.maxUnavailable }}
  {{- end }}
  replicas: {{ .Values.replicaCount }}
  template:
    metadata:
      labels:
       app: {{ template "name" . }}-{{ .Values.name }}
       chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
    spec:
      imagePullSecrets:
        - name: {{ .Values.image.secret }}
      volumes:
      - configMap:
          name: kube-api-cfg
        name: kube-api-volume
      containers:
        - name: {{ .Chart.Name }}-{{ .Values.name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          volumeMounts:
            - mountPath: /cfg
              name: kube-api-volume
          env:
            {{- range $key, $val := .Values.env }}
            - name: {{ $key }}
              value: {{ $val | quote }}
            {{- end }}
          ports:
            - containerPort: {{ .Values.service.internalPort }}
          resources:
{{ toYaml .Values.resources | indent 12 }}
    {{- if .Values.nodeSelector }}
      nodeSelector:
{{ toYaml .Values.nodeSelector | indent 8 }}
    {{- end }}
